### ISSUE TITLE
Do math in the IOMap

### ISSUE THREAD

**Issue by natedileas** [jmaggio14/imagepypelines#66]
Make IoMaps able to understand math that relates the input and output shape. This will allow a more complex and powerful system.

## Proposed User Syntax
The syntax I'm envisioning it is something like this:

### Flattening an image:
```
map = ip.IoMap({
        ArrayType('m,n,o'):ArrayType('n*m*o')
    })
```

### Padding an image on all sides by `a`, a parameter passed by the user:
```
map = ip.IoMap({
        ArrayType('m,n,o'):ArrayType('m+a*2, n+a*2, o')
    })
```

## Implementation Side
This approach would require a compilation of the string with some special syntax we cook up. I'd see the IoMap side as something like this:

### Propagation pseudo code
```
ina = 'm,n,o'
outb = 'm+2,n+2,o'

exec("{in_str} = inshape; outshape = eval({out_str})".format(in_str=ina, out_str=outb))
```

### Matching pseudo code
```
matcha = 'm,n,o'
matchb = 'i,j,k'

exec("a = {str1};b = {str2}; match = all([a[i]==b[i] for i in range(len(b))])".format(str1=matcha, str2=matchb))
```

Other syntax possibilities? The major downside of the way I'm proposing this is that it makes presenting helpful debugging/warning/error information to the user more difficult.

**Comment by jmaggio14** [comment]
maybe we can use sympy for this?

https://docs.sympy.org/latest/tutorial/basic_operations.html#substitution
https://docs.sympy.org/latest/tutorial/printing.html#printers
